### ISSUE TITLE
not able to access enterprise AIP

### ISSUE THREAD

**Issue by ciekawy** [sindresorhus/notifier-for-github-chrome#110]
after configuring some github enterprise URL and provided valid token configured for repo and notification access I'm getting
```
{
  "message": "Must authenticate to access this API.",
  "documentation_url": "https://developer.github.com/enterprise/2.6/v3"
}
```

Not sure if I'm doing something wrong or there is some other issue...

**Comment by gcochard** [comment]
Looks like the GH:E API has not changed since this code was written, please try making a request against the API endpoint [using curl](https://developer.github.com/enterprise/2.6/v3/#authentication) to rule out a bad token. If it persists, try creating a new token. Also ensure there are no leading or trailing characters in the token field, only the token alone.

**Comment by ciekawy** [comment]
got it after inspecting the extension :) I was providing the URL including the `/api/v3/` instead of just the github root URL. Probably there could be some sanity check on this...
