### ISSUE TITLE
Installation on Firefox?

### ISSUE THREAD

**Issue by Cadair** [sindresorhus/notifier-for-github-chrome#118]
Hi, I am trying to swap out my extensions to enable multiprocess. I followed the link from the firefox repository to here but there is no obvious way to install this into firefox.

Can this extension be put into the Mozilla addon site?
Thanks!

**Comment by sindresorhus** [comment]
> I followed the link from the firefox repository to here but there is no obvious way to install this into firefox.

Google is your friend.

> Can this extension be put into the Mozilla addon site?

If someone offers to do it or automates the process, sure.

**Comment by Cadair** [comment]
> Google is your friend.

As always. I did manage to get it installed from the chrome webstore! My comment was really that your readme has no information on this for less technically savvy users. I will open a PR to the readme later.

Having got this installed in firefox, when I click on the link nothing happens I assume this is a bug? If so I will open a new issue.

**Comment by ExE-Boss** [comment]
### I recommend looking at the following resources:
- https://developer.mozilla.org/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
- https://developer.mozilla.org/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on
- https://developer.mozilla.org/Add-ons/WebExtensions/WebExtensions_and_the_Add-on_ID
- https://developer.mozilla.org/Add-ons/WebExtensions/Publishing_your_WebExtension

### Add-on ID and the minimum supported Firefox version
Since this addon has been published to AMO in the past, it is recommended that you set the Add-on ID to what it was in the legacy version.

This is achieved by adding the [`applications`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications) key to `manifest.json`:
```json5
"applications": {
	"gecko": {
		// This is the Add-on ID as it was
		// in the SDK version of the Add-on:
		"id": "jid1-DMjSwVBPnk7a1Q@jetpack",

		// This is the minimum Firefox version that supports
		// all the APIs needed by this WebExtension.
		// I have looked through the source code,
		// and it should be correct. (The `permissions` API
		// will be implemented in Firefox 55 (Bug 1197420))
		"strict_min_version": "55.0"

		// If you don’t care about the `permissions` API,
		// then you need to set `strict_min_version` to `52.0`
		// and create a dummy version of `PermissionsService`
		// for the Firefox version that auto-resolves
		// all Promises to `false` until Firefox 55.0
		// gets released.
	}
}
```

### Blocking bugs:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1197420

**Comment by tw0517tw** [comment]
https://github.com/mozilla/web-ext/issues/804

It seems Mozilla will add publishing command to the `web-ext` CLI. Maybe we could have auto-publishing (to Mozilla addon site) then.

**Comment by umpirsky** [comment]
I'm on `57.0b4 (64-bit)`, is there any way to install it there? Or we need to wait to be submitted to addons.mozilla.org?

**Comment by ExE-Boss** [comment]
@umpirsky You can use [Chrome Store Foxified](https://addons.mozilla.org/firefox/addon/chrome-store-foxified/) to install the [Chrome version](https://chrome.google.com/webstore/detail/notifier-for-github/lmjdlojahmbbcodnpecnjnmlddbkjhnn), or just drag and drop the Chrome version into `about:debugging`’s temporary load extension.

**Comment by umpirsky** [comment]
Thanks, unfortunately it's not compatible with `57.0b4 (64-bit)`.

![screenshot from 2017-10-04 18-15-14](https://user-images.githubusercontent.com/208957/31186825-155172d2-a930-11e7-8bf8-8b05e66a7bf5.png)
