### ISSUE TITLE
Switch from XHR to Fetch

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github-chrome#70]
In https://github.com/sindresorhus/notifier-for-github-chrome/blob/master/extension/api.js

Would make the code a lot cleaner.

https://developer.mozilla.org/en/docs/Web/API/Fetch_API

It's been in Chrome since v42.

**Comment by sindresorhus** [comment]
@fstoerkle @YuriSolovyov @gcochard Any of you interested in working on this?

**Comment by YuriSolovyov** [comment]
@sindresorhus yes, I already used fetch in notifications PR, and it looks quite nice, esp. with regard to promises.

**Comment by YuriSolovyov** [comment]
@sindresorhus after using it for a while, I don't think it is good idea anymore, because it sends pre-filight OPTIONS request effectively doubling number of requests (setting `cors` request type didn't help), it also downcases headers for some reason, which didn't happen for XHR.

It might be that I got something wrong, but it's my experience ATM.
We might want to use some good library for this, or revisit it later.

**Comment by sindresorhus** [comment]
@YuriSolovyov It should only send a preflight when using CORS. Sounds like a `fetch` bug. I don't think the preflight requests will have any noticeable performance impact.
